name: run-tests

on: ['push']

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    name: Runs tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: |
          composer install --no-interaction

      - name: Execute unit tests
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-xml ./tests/coverage

      - name: Check coverage
        run: php coverage.php ./tests/coverage/index.xml 100

      - name: Execute infection tests
        run: ./vendor/bin/infection -s